//! Generated by game/industrial/generate.py; source geometry and collision share dimensions.
pub const chunk_span: f32 = 64;
pub const boxes = .{
    .{
        .{ .position = .{ -20, 4.0, -20 }, .half_extents = .{ 9.0, 4.0, 9.0 } },
        .{ .position = .{ 20, 3.0, -20 }, .half_extents = .{ 10.0, 3.0, 9.0 } },
        .{ .position = .{ -20, 2.5, 18 }, .half_extents = .{ 10.0, 2.5, 7.0 } },
        .{ .position = .{ 20, 4.5, 20 }, .half_extents = .{ 9.0, 4.5, 10.0 } },
    },
    .{
        .{ .position = .{ 44, 4.5, -20 }, .half_extents = .{ 9.0, 4.5, 9.0 } },
        .{ .position = .{ 84, 3.5, -20 }, .half_extents = .{ 10.0, 3.5, 9.0 } },
        .{ .position = .{ 44, 4.0, 18 }, .half_extents = .{ 10.0, 4.0, 7.0 } },
        .{ .position = .{ 84, 4.0, 20 }, .half_extents = .{ 9.0, 4.0, 10.0 } },
    },
    .{
        .{ .position = .{ -20, 5.0, 44 }, .half_extents = .{ 9.0, 5.0, 9.0 } },
        .{ .position = .{ 20, 4.0, 44 }, .half_extents = .{ 10.0, 4.0, 9.0 } },
        .{ .position = .{ -20, 4.0, 82 }, .half_extents = .{ 10.0, 4.0, 7.0 } },
        .{ .position = .{ 20, 3.5, 84 }, .half_extents = .{ 9.0, 3.5, 10.0 } },
    },
    .{
        .{ .position = .{ 44, 5.5, 44 }, .half_extents = .{ 9.0, 5.5, 9.0 } },
        .{ .position = .{ 84, 4.5, 44 }, .half_extents = .{ 10.0, 4.5, 9.0 } },
        .{ .position = .{ 44, 4.0, 82 }, .half_extents = .{ 10.0, 4.0, 7.0 } },
        .{ .position = .{ 84, 3.0, 84 }, .half_extents = .{ 9.0, 3.0, 10.0 } },
    },
};
pub const navigation_positions = [_][2]f32{ .{ -8, -8 }, .{ 0, -8 }, .{ 8, -8 }, .{ 8, 0 }, .{ 8, 8 }, .{ 0, 8 }, .{ -8, 8 }, .{ -8, 0 }, .{ 31, 8 }, .{ -31, 8 }, .{ 8, 31 }, .{ 8, -31 } };
pub const navigation_edge_capacity: usize = 26;
pub const navigation_degree: usize = 3;
